<div role="main">
    <h2><?php echo $this->data; ?></h2>

    <h3>Functions</h3>
    <ul>
        <li>echo $this->_renderPartial('partial');</li>
        <li>echo $this->_renderLayoutPartial('layoutPartial');</li>
        <li>echo $this->_getData('data');</li>
    </ul>

    <h3>Plugins</h3>
    <ul>
        <li>Contact plugin</li>
        <li>Navigation plugin</li>
    </ul>
</div>
<div class="sidebar">
    <?php echo $this->_renderPartial('sidebar'); ?>
</div>