<?php
    // HEAD tag
    echo $this->_renderLayoutPartial('head');
?>
<body>
<!--[if lt IE 7]>
<p class=chromeframe>
    Your browser is <em>ancient!</em>
    <a href="http://browsehappy.com/">Upgrade to a different browser</a> or
    <a href="http://www.google.com/chromeframe/?redirect=true">install Google
    Chrome Frame</a> to experience this site.
</p>
<![endif]-->
<header>
    <h1>PHP Micro Framework</h1>
</header>
<?php
    /*** CONTENT BEGIN! ***/

    echo $this->renderView();

    /*** CONTENT END! ***/
?>
<footer>

</footer>
<?php
    echo $this->renderLayoutPartial('foot');
?>